Repository Book-Job/Frontend, pull requests merged in 2025-06, with the labels that each got.

#100 [feature-24/feat] 모달창 중앙화(스타일 수정) & Toastify css 적용 안 되는 오류 수정 & 검색 스타일 수정 완료
  src/App.jsx
  src/assets/icons/common/common_search_cancel_button.svg
  src/components/app/MobileWorkBoard.jsx
  src/components/common/LoginRequiredAlert.jsx
  src/components/web/Alert.jsx
  src/components/web/Modal.jsx
  src/components/web/SearchBar.jsx
  src/components/web/WorkBoard.jsx
  src/domains/Find/detail/FindPwEnterID.jsx
  src/domains/community/detail/page/DetailCommunityPage.jsx
  src/domains/job/main/page/JobMainPage.jsx
  src/domains/job/recruitment/detail/page/RecruitmentDetailPage.jsx
  src/domains/job/search/detail/page/JobSeekDetailPage.jsx
  src/domains/login/common/components/JoinForm.jsx
  src/domains/login/common/components/LoginForm.jsx
  src/routes/ProtectedRoute.jsx
  src/store/modal/useModalStore.js
  src/stories/Alert.stories.jsx
  src/stories/MobileShare.stories.jsx
  src/stories/ShareViews.stories.jsx
  src/utils/toastService.js
  tailwind.config.js
Labels: 🐞 BugFix, ✨ Feature, 🎨 Publishing

#102 [publishing-18/style] 헤더 디자인 수정 & 글 작성 버튼 디자인 수정 완료
  src/assets/icons/common/common_pencil2.svg
  src/components/common/ScrollAndWriteButton.jsx
  src/components/web/Header.jsx
  src/components/web/Modal.jsx
  src/domains/Find/common/components/OTPInput.jsx
  src/domains/my/detail/EditProfile.jsx
  src/domains/my/detail/components/ProfileInfo.jsx
  tailwind.config.js
Labels: 🎨 Publishing

#103 [feature-23/feat] 자유게시판 임시저장 기능 / 베스트글 정렬 수정
  package.json
  src/components/web/InputBox.jsx
  src/components/web/PwInputBox.jsx
  src/domains/Find/services/useFindIDServices.js
  src/domains/community/write/components/WriteCommunityPostForm.jsx
  src/domains/community/write/page/WriteCommunityPostPage.jsx
  src/domains/login/common/components/KakaoLogin.jsx
  src/domains/login/common/components/LoginForm.jsx
  src/domains/login/common/components/NaverLogin.jsx
  src/domains/login/common/components/SnsLogin.jsx
  src/domains/login/page/KakaoSuccess.jsx
  src/domains/login/page/LoginMain.jsx
  src/domains/login/page/NaverSuccess.jsx
  src/domains/login/services/useLoginServices.js
  src/domains/main/common/components/BestList.jsx
  src/domains/main/common/components/BoardButton.jsx
  src/domains/main/common/components/Modal.jsx
  src/domains/main/main/MainPage.jsx
  src/domains/my/detail/EditProfile.jsx
  src/domains/my/detail/MyDrafts.jsx
  src/domains/my/detail/components/MyDraftsList.jsx
  src/domains/my/detail/components/ProfileInfo.jsx
  src/routes/Layout.jsx
  src/routes/RouterPath.js
  src/routes/routes.jsx
  src/store/find/useFindPWStore.js
  src/store/login/useAuthStore.js
  src/store/mypage/useDraftStore.js
  yarn.lock
Labels: ✨ Feature, 🚧 work in process

#105 [feature-25/feat] 구인구직 메인 스타일 수정 & 디버깅용 콘솔 & 주석 삭제
  src/components/app/MobileMainHeader.jsx
  src/components/web/Header.jsx
  src/components/web/InputBox.jsx
  src/components/web/PwInputBox.jsx
  src/domains/Find/common/components/InputEmail.jsx
  src/domains/Find/common/components/OTPInput.jsx
  src/domains/Find/detail/ChangePwPage.jsx
  src/domains/Find/detail/FindIDCompletePage.jsx
  src/domains/Find/detail/FindPwCheckIDPage.jsx
  src/domains/Find/detail/FindPwEnterID.jsx
  src/domains/Find/page/FindIDPage.jsx
  src/domains/Find/services/useFindIDServices.js
  src/domains/Find/services/useFindPWServices.js
  src/domains/community/comment/components/CommentForm.jsx
  src/domains/community/comment/components/CommentList.jsx
  src/domains/community/service/commentService.js
  src/domains/community/service/postService.js
  src/domains/community/service/useSearchPosts.js
  src/domains/community/write/components/WriteCommunityPostForm.jsx
  src/domains/community/write/page/WriteCommunityPostPage.jsx
  src/domains/job/common/components/JobPostSortDropDown.jsx
  src/domains/job/common/service/postService.js
  src/domains/job/main/page/JobMainPage.jsx
  src/domains/job/main/service/jobMainService.js
  src/domains/job/scrap/service/scrapService.js
  src/domains/login/common/components/EmailInput.jsx
  src/domains/login/common/components/IDInput.jsx
  src/domains/login/common/components/JoinForm.jsx
  src/domains/login/common/components/LoginForm.jsx
  src/domains/login/common/components/NicknameInput.jsx
  src/domains/login/page/KakaoSuccess.jsx
  src/domains/login/services/useJoinServices.js
  src/domains/login/services/useLoginServices.js
  src/domains/main/common/components/BoardButton.jsx
  src/domains/main/main/MainPage.jsx
  src/domains/main/services/useBestServices.js
  src/domains/my/detail/EditPassword.jsx
  src/domains/my/detail/EditProfile.jsx
  src/domains/my/detail/MyDrafts.jsx
  src/domains/my/detail/MyScrap.jsx
  src/domains/my/detail/components/MembershipPwCheck.jsx
  src/domains/my/detail/components/MyDraftsList.jsx
  src/domains/my/detail/components/PostList.jsx
  src/domains/my/page/MyPage.jsx
  src/domains/my/services/useMyBoardServices.js
  src/domains/my/services/userMyDataServices.js
  src/routes/RouterPath.js
  src/services/api/Axios.js
  src/store/login/useAuthStore.js
  src/store/main/useBestStore.js
  src/store/mypage/useDraftStore.js
  src/store/mypage/useMyBoardStore.js
  src/stories/Button.stories.jsx
  src/stories/MobileFreeBoard.stories.jsx
  src/stories/MobileWorkBoard.stories.jsx
  src/stories/SearchBar.stories.jsx
  src/stories/TagIcon.stories.jsx
  src/stories/WorkBoard.stories.jsx
Labels: ✨ Feature, 🎨 Publishing

#108 [release-v1.0] 1차 배포 완료
  .github/workflows/deploy.yml
  .gitignore
  lighthouserc.json
  src/services/api/axios.js
  src/stories/MobileFreeBoard.stories.jsx
Labels: 🪐 Deploy

#113 [release-v.1.1] 2차 release
  index.html
  public/favicon.svg
  public/metatag.png
  src/components/app/MobileHeader.jsx
  src/components/app/MobileMainHeader.jsx
  src/components/web/Header.jsx
  src/domains/job/main/page/JobMainPage.jsx
  src/domains/login/page/LoginMain.jsx
  src/routes/Layout.jsx
Labels: 🪐 Deploy

#114 [feature-27/feat] 모바일 버전 디자인 변경 / 로그아웃 기능 수정
  src/components/web/Header.jsx
  src/domains/Find/common/components/InputEmail.jsx
  src/domains/Find/common/components/OTPInput.jsx
  src/domains/Find/common/components/PageBox.jsx
  src/domains/Find/common/components/PageTitle.jsx
  src/domains/Find/detail/FindIDCompletePage.jsx
  src/domains/Find/detail/FindPwCheckIDPage.jsx
  src/domains/Find/detail/FindPwEnterID.jsx
  src/domains/Find/page/FindIDPage.jsx
  src/domains/job/recruitment/write/page/WriteRecruitmentPostPage.jsx
  src/domains/login/common/components/DomainSelector.jsx
  src/domains/login/common/components/JoinButton.jsx
  src/domains/login/common/components/JoinForm.jsx
  src/domains/login/common/components/KakaoLogin.jsx
  src/domains/login/common/components/LoginForm.jsx
  src/domains/login/common/components/NaverLogin.jsx
  src/domains/login/common/components/SnsLogin.jsx
  src/domains/login/page/KakaoSuccess.jsx
  src/domains/login/services/useLoginServices.js
  src/domains/main/common/components/BoardButton.jsx
  src/domains/main/main/MainPage.jsx
  src/domains/my/detail/EditPassword.jsx
  src/domains/my/detail/EditProfile.jsx
  src/domains/my/mypage/components/MyActivity.jsx
  src/domains/my/mypage/components/MyData.jsx
  src/routes/routes.jsx
  src/store/login/useAuthStore.js
Labels: 🐞 BugFix, 🎨 Publishing, 🚧 work in process

#118 [feature-28/feat] 스크랩 타입 반영 & 반응형 수정 완료
  src/components/web/Header.jsx
  src/components/web/Modal.jsx
  src/components/web/WorkBoard.jsx
  src/domains/community/service/postService.js
  src/domains/job/common/components/form/PersonalInfo.jsx
  src/domains/job/main/service/jobMainService.js
  src/domains/job/recruitment/components/form/ClosingDate.jsx
  src/domains/job/recruitment/components/form/Experience.jsx
  src/domains/job/scrap/service/scrapService.js
  src/domains/my/detail/MyScrap.jsx
Labels: 🐞 BugFix, ✨ Feature, 🎨 Publishing

#119 [release-v1.3] 반응형 & 기능 적용
  src/components/web/Header.jsx
  src/components/web/Modal.jsx
  src/components/web/WorkBoard.jsx
  src/domains/community/service/postService.js
  src/domains/job/common/components/form/PersonalInfo.jsx
  src/domains/job/main/service/jobMainService.js
  src/domains/job/recruitment/components/form/ClosingDate.jsx
  src/domains/job/recruitment/components/form/Experience.jsx
  src/domains/job/scrap/service/scrapService.js
  src/domains/my/detail/MyScrap.jsx
Labels: 🪐 Deploy

#131 [bug-07/fix] 자유게시판 글 검색 & 특정 사용자가 작성한 글 조회 수정 완료
  lighthouserc.json
  src/components/app/MobileFreeBoard.jsx
  src/components/web/FreeBoard.jsx
  src/domains/community/detail/page/UserPosts.jsx
  src/domains/community/main/page/CommunityMainPage.jsx
  src/domains/community/service/postService.js
  src/domains/community/service/useSearchPosts.js
  src/domains/job/main/service/jobMainService.js
  src/routes/RouterPath.js
Labels: 🐞 BugFix

#134 [feature-29/feat] tanstack-query를 사용한 무한스크롤 & react-helmet 적용 완료
  package.json
  src/App.jsx
  src/components/common/SeoHelmet.jsx
  src/domains/community/detail/components/RelatedPosts.jsx
  src/domains/community/main/hook/useCommunityPosts.js
  src/domains/community/main/page/CommunityMainPage.jsx
  src/domains/job/common/components/JobInfiniteScroll.jsx
  src/domains/job/main/page/JobMainPage.jsx
  src/domains/job/recruitment/detail/components/RelatedRecruitmentPosts.jsx
  src/domains/job/search/detail/components/RelatedJobSearchPosts.jsx
  src/domains/main/main/MainPage.jsx
  src/main.jsx
  yarn.lock
Labels: ✨ Feature, 🚀 Refactor

#133 [feature-30/feat] 소셜 로그인 마무리/ 구인구직 임시저장 기능 추가
  src/components/app/MobileMainHeader.jsx
  src/components/web/Header.jsx
  src/domains/community/write/components/WriteCommunityPostForm.jsx
  src/domains/job/recruitment/components/form/WriteRecruitmentPostingForm.jsx
  src/domains/job/recruitment/edit/page/EditRecruitmentPostPage.jsx
  src/domains/job/recruitment/write/page/WriteRecruitmentPostPage.jsx
  src/domains/login/common/components/EmailInput.jsx
  src/domains/login/common/components/KakaoLogin.jsx
  src/domains/login/common/components/NicknameInput.jsx
  src/domains/login/page/KakaoRedirectHandler.jsx
  src/domains/login/page/KakaoSuccess.jsx
  src/domains/login/page/NaverSuccess.jsx
  src/domains/login/services/useLoginServices.js
  src/domains/my/detail/MyDrafts.jsx
  src/domains/my/detail/MyPost.jsx
  src/domains/my/detail/MyScrap.jsx
  src/domains/my/detail/components/MyDraftsList.jsx
  src/domains/my/detail/components/PostList.jsx
  src/hooks/writePost/useDraftHandler.js
  src/routes/routes.jsx
  src/services/api/axios.js
  src/store/login/useAuthStore.js
  src/store/mypage/useFreeDraftStore.js
  src/store/mypage/useRecruitmentDraftStore.js
Labels: ✨ Feature

#136 [release-v1.5] 5차 버스 출발
  package.json
  src/App.jsx
  src/components/app/MobileMainHeader.jsx
  src/components/common/SeoHelmet.jsx
  src/components/web/Header.jsx
  src/domains/community/detail/components/RelatedPosts.jsx
  src/domains/community/main/hook/useCommunityPosts.js
  src/domains/community/main/page/CommunityMainPage.jsx
  src/domains/community/write/components/WriteCommunityPostForm.jsx
  src/domains/job/common/components/JobInfiniteScroll.jsx
  src/domains/job/main/page/JobMainPage.jsx
  src/domains/job/recruitment/components/form/WriteRecruitmentPostingForm.jsx
  src/domains/job/recruitment/detail/components/RelatedRecruitmentPosts.jsx
  src/domains/job/recruitment/edit/page/EditRecruitmentPostPage.jsx
  src/domains/job/recruitment/write/page/WriteRecruitmentPostPage.jsx
  src/domains/job/search/detail/components/RelatedJobSearchPosts.jsx
  src/domains/login/common/components/EmailInput.jsx
  src/domains/login/common/components/KakaoLogin.jsx
  src/domains/login/common/components/NicknameInput.jsx
  src/domains/login/page/KakaoRedirectHandler.jsx
  src/domains/login/page/KakaoSuccess.jsx
  src/domains/login/page/NaverSuccess.jsx
  src/domains/login/services/useLoginServices.js
  src/domains/main/main/MainPage.jsx
  src/domains/my/detail/MyDrafts.jsx
  src/domains/my/detail/MyPost.jsx
  src/domains/my/detail/MyScrap.jsx
  src/domains/my/detail/components/MyDraftsList.jsx
  src/domains/my/detail/components/PostList.jsx
  src/hooks/writePost/useDraftHandler.js
  src/main.jsx
  src/routes/routes.jsx
  src/services/api/axios.js
  src/store/login/useAuthStore.js
  src/store/mypage/useFreeDraftStore.js
  src/store/mypage/useRecruitmentDraftStore.js
  yarn.lock
Labels: 🪐 Deploy

#137 [feature-30/feat] fix: 토큰 bearer수정
  src/domains/login/page/NaverSuccess.jsx
  src/services/api/axios.js
  src/store/login/useAuthStore.js
Labels: 🐞 BugFix

#140 [release-0.7] presigned-url test
  package.json
  src/components/common/WriteEditor.jsx
  src/domains/community/detail/hook/useEditPost.js
  src/domains/community/detail/page/DetailCommunityPage.jsx
  src/domains/community/write/components/WriteCommunityPostForm.jsx
  tailwind.config.js
  yarn.lock
Labels: 🪐 Deploy

#143 [release-v0.7] 7차 버스 출발
  src/domains/login/page/KakaoSuccess.jsx
  src/domains/login/page/NaverSuccess.jsx
  src/domains/login/services/useLoginServices.js
  src/services/api/axios.js
  src/store/login/useAuthStore.js
Labels: 🪐 Deploy

#147 [feature-30/feat] 로그인 연장 기능 수정3
  src/store/login/useAuthStore.js
Labels: 🐞 BugFix

#148 [release-v0.9] 9차 버스 출발
  src/store/login/useAuthStore.js
Labels: 🪐 Deploy

#151 [release-v0.10] 10차 버스 출발
  src/domains/login/services/useLoginServices.js
Labels: 🪐 Deploy

#153 [release-v0.11] 11차 버스 출발
  src/services/api/axios.js
  src/store/login/useAuthStore.js
Labels: 🪐 Deploy

#156 [feature-30/feat] 로그인 연장 기능 수정7
  src/services/api/axios.js
Labels: 🐞 BugFix

#157 [feature-30/feat] 로그인 연장 기능 수정8
  src/services/api/axios.js
Labels: 🐞 BugFix

#158 [release-v0.13] 13차 버스 출발
  src/services/api/axios.js
Labels: 🪐 Deploy

#161 [feature-30/feat] 로그인 연장 기능 수정10
  src/services/api/axios.js
  src/store/login/useAuthStore.js
Labels: 🐞 BugFix

#162 [release-v0.15] 15차 버스 출발
  src/services/api/axios.js
  src/store/login/useAuthStore.js
Labels: 🪐 Deploy

#164 [release-v0.16] 16차 버스 출발
  src/services/api/axios.js
Labels: 🪐 Deploy

#167 [release-v0.17] 17차 버스 출발
  package.json
  src/components/app/MobileFreeBoard.jsx
  src/components/common/WriteEditor.jsx
  src/components/common/editor/EditorToolbar.jsx
  src/components/common/editor/ImageBubbleMenu.jsx
  src/components/common/editor/WriteEditor.jsx
  src/domains/community/detail/page/DetailCommunityPage.jsx
  src/domains/community/detail/util/draftjsUtils.js
  src/domains/community/write/components/WriteCommunityPostForm.jsx
  src/domains/community/write/hook/useCommunityPostForm.js
  src/domains/job/common/components/form/PostContent.jsx
  src/domains/job/main/page/JobMainPage.jsx
  src/domains/job/recruitment/components/form/WriteRecruitmentPostingForm.jsx
  src/domains/job/recruitment/edit/page/EditRecruitmentPostPage.jsx
  src/domains/job/search/components/WriteJobSearchPostingForm.jsx
  src/domains/job/search/edit/page/EditJobSeekPostPage.jsx
  src/hooks/writePost/useEditorInstance.js
  yarn.lock
Labels: 🪐 Deploy

#170 [feature-33/feat] 푸터 수정 & 구글 폼 연결 & 공유하기 기능 완성
  src/components/app/MobileShare.jsx
  src/components/app/MobileSidebar.jsx
  src/components/web/Footer.jsx
  src/components/web/Header.jsx
  src/domains/community/detail/page/DetailCommunityPage.jsx
  src/domains/job/recruitment/detail/page/RecruitmentDetailPage.jsx
  src/domains/job/search/detail/page/JobSeekDetailPage.jsx
  src/routes/Layout.jsx
Labels: ✨ Feature, 🎨 Publishing

#171 [feature-32/feat]소셜 로그인 회원 탈퇴 임시기능 / 비밀번호 변경 금지
  src/components/common/ChooseWriteForm.jsx
  src/components/common/ScrollAndWriteButton.jsx
  src/components/web/Header.jsx
  src/domains/login/services/useLoginServices.js
  src/domains/my/detail/EditProfile.jsx
  src/domains/my/detail/MyPost.jsx
  src/domains/my/detail/components/MyPostHead.jsx
  src/domains/my/detail/components/PostList.jsx
  src/domains/my/detail/components/ProfileInfo.jsx
  src/domains/my/mypage/components/MyActivity.jsx
  src/domains/my/mypage/components/MyData.jsx
  src/domains/my/services/useMyBoardServices.js
  src/routes/routes.jsx
  src/services/api/axios.js
  src/store/modal/useWriteModalStore.js
  src/store/mypage/useMyBoardStore.js
  src/utils/urls.js
Labels: ✨ Feature

#181 [release-v0.19] 19차 버스 출발
  src/store/login/useAuthStore.js
Labels: 🪐 Deploy

#175 [bug-08/fix] 검색 수정 & 구인,구직 메인페이지 글 작성 삭제 반영 실시간으로 못하는 오류 & 스크랩 새로고침 하면 풀리는 오류 수정
  src/components/common/editor/EditorToolbar.jsx
  src/components/web/Footer.jsx
  src/components/web/SearchBar.jsx
  src/domains/community/detail/page/DetailCommunityPage.jsx
  src/domains/community/service/useSearchPosts.js
  src/domains/job/common/components/JobInfiniteScroll.jsx
  src/domains/job/common/components/JobPostSortDropDown.jsx
  src/domains/job/common/components/form/PostContent.jsx
  src/domains/job/common/constants/sortOptions.js
  src/domains/job/common/hook/usePostSubmit.js
  src/domains/job/common/hook/useSortOptions.js
  src/domains/job/main/components/JobDropDown.jsx
  src/domains/job/main/components/JobPostList.jsx
  src/domains/job/main/hook/useJobMainState.js
  src/domains/job/main/page/JobMainPage.jsx
  src/domains/job/recruitment/detail/components/RelatedRecruitmentPosts.jsx
  src/domains/job/recruitment/detail/page/RecruitmentDetailPage.jsx
  src/domains/job/scrap/service/scrapService.js
  src/domains/job/scrap/store/useScrapStore.js
  src/domains/job/search/detail/components/RelatedJobSearchPosts.jsx
  src/domains/job/search/detail/page/JobSeekDetailPage.jsx
  src/domains/my/detail/MyScrap.jsx
Labels: 🐞 BugFix, 🚧 work in process, 🚀 Refactor

#184 [release-v0.20] 20차 버스 출발
  src/components/app/MobileSidebar.jsx
  src/components/common/editor/EditorToolbar.jsx
  src/components/web/Footer.jsx
  src/components/web/Header.jsx
  src/components/web/SearchBar.jsx
  src/domains/community/detail/page/DetailCommunityPage.jsx
  src/domains/community/service/useSearchPosts.js
  src/domains/error/page/ErrorPage.jsx
  src/domains/job/common/components/JobInfiniteScroll.jsx
  src/domains/job/common/components/JobPostSortDropDown.jsx
  src/domains/job/common/components/form/PostContent.jsx
  src/domains/job/common/constants/sortOptions.js
  src/domains/job/common/hook/usePostSubmit.js
  src/domains/job/common/hook/useSortOptions.js
  src/domains/job/main/components/JobDropDown.jsx
  src/domains/job/main/components/JobPostList.jsx
  src/domains/job/main/hook/useJobMainState.js
  src/domains/job/main/page/JobMainPage.jsx
  src/domains/job/recruitment/detail/components/RelatedRecruitmentPosts.jsx
  src/domains/job/recruitment/detail/page/RecruitmentDetailPage.jsx
  src/domains/job/scrap/service/scrapService.js
  src/domains/job/scrap/store/useScrapStore.js
  src/domains/job/search/detail/components/RelatedJobSearchPosts.jsx
  src/domains/job/search/detail/page/JobSeekDetailPage.jsx
  src/domains/main/main/MainPage.jsx
  src/domains/my/detail/MyScrap.jsx
  src/utils/urls.js
Labels: 🪐 Deploy

#176 [bug-09/fix] 회원가입 이메일 @ / 소셜 로그인 반응
  src/assets/icons/common/kakaoIcon_s.svg
  src/assets/icons/common/naverIcon_s.svg
  src/components/web/Button.jsx
  src/components/web/LabelWithInput.jsx
  src/domains/Find/common/components/InputEmail.jsx
  src/domains/Find/common/components/OTPInput.jsx
  src/domains/Find/page/FindIDPage.jsx
  src/domains/login/common/components/CustomDomain.jsx
  src/domains/login/common/components/DomainSelector.jsx
  src/domains/login/common/components/EmailInput.jsx
  src/domains/login/common/components/JoinButton.jsx
  src/domains/login/common/components/JoinForm.jsx
  src/domains/login/common/components/KakaoLogin.jsx
  src/domains/login/common/components/NaverLogin.jsx
  src/domains/login/common/components/SnsLogin.jsx
  src/domains/login/page/LoginMain.jsx
  src/domains/my/detail/EditProfile.jsx
Labels: 🐞 BugFix, 🎨 Publishing

#191 [publishing-22/style] 퍼블리싱 수정
  src/App.jsx
  src/components/app/MobileFreeBoard.jsx
  src/components/web/FreeBoard.jsx
  src/components/web/Modal.jsx
  src/domains/community/detail/components/RelatedPosts.jsx
  src/domains/community/main/page/CommunityMainPage.jsx
  src/domains/job/recruitment/components/form/ClosingDate.jsx
  src/domains/job/recruitment/detail/page/RecruitmentDetailPage.jsx
  src/domains/job/search/detail/page/JobSeekDetailPage.jsx
  src/utils/toastService.js
Labels: 🎨 Publishing

#193 [feature-34/fix]임시저장 중복알림 수정/ 삭제 알림 추가/ 내용 없음 표시 수정
  src/components/common/ScrollAndWriteButton.jsx
  src/components/common/editor/WriteEditor.jsx
  src/domains/community/write/components/WriteCommunityPostForm.jsx
  src/domains/my/detail/components/MyDraftsList.jsx
  src/domains/my/mypage/components/MyActivity.jsx
  src/hooks/login/useInputBox.test.js
  src/services/api/axios.js
  src/store/mypage/useFreeDraftStore.js
  src/stories/InputBox.stories.jsx
  src/stories/PwInputBox.stories.jsx
  tailwind.config.js
Labels: 🐞 BugFix

#194 [release-v0.23] 23차 버스 출발
  src/components/common/ScrollAndWriteButton.jsx
  src/components/common/editor/WriteEditor.jsx
  src/components/web/Modal.jsx
  src/components/web/PwInputBox.jsx
  src/domains/community/write/components/WriteCommunityPostForm.jsx
  src/domains/community/write/page/WriteCommunityPostPage.jsx
  src/domains/job/common/components/form/EmploymentType.jsx
  src/domains/job/common/components/form/PostContent.jsx
  src/domains/job/recruitment/components/form/ClosingDate.jsx
  src/domains/job/recruitment/components/form/WriteRecruitmentPostingForm.jsx
  src/domains/job/recruitment/write/page/WriteRecruitmentPostPage.jsx
  src/domains/job/search/components/WriteJobSearchPostingForm.jsx
  src/domains/job/search/write/page/WriteJobSearchPostPage.jsx
  src/domains/login/common/components/CustomDomain.jsx
  src/domains/login/common/components/DomainSelector.jsx
  src/domains/login/common/components/EmailInput.jsx
  src/domains/login/common/components/PasswordInput.jsx
  src/domains/my/detail/EditProfile.jsx
  src/domains/my/detail/MyDrafts.jsx
  src/domains/my/detail/MyPost.jsx
  src/domains/my/detail/components/MyDraftsList.jsx
  src/domains/my/detail/components/MyPostHead.jsx
  src/domains/my/detail/components/PostList.jsx
  src/domains/my/mypage/components/MyActivity.jsx
  src/hooks/login/useInputBox.test.js
  src/hooks/writePost/useDraftHandler.js
  src/hooks/writePost/useSaveDraft.js
  src/services/api/axios.js
  src/store/mypage/useFreeDraftStore.js
  src/stories/InputBox.stories.jsx
  src/stories/PwInputBox.stories.jsx
  tailwind.config.js
Labels: 🪐 Deploy

#199 [feature-36/feat]내가 작성한 글 무한스크롤 / 최근본 목록 추가/ 비밀번호 변경 페이지 반응형 변경
  src/components/web/BoardCategory.jsx
  src/components/web/FreeBoard.jsx
  src/components/web/WorkBoard.jsx
  src/domains/Find/common/components/NewPasswordInput.jsx
  src/domains/Find/detail/ChangePwPage.jsx
  src/domains/community/detail/page/DetailCommunityPage.jsx
  src/domains/job/main/page/JobMainPage.jsx
  src/domains/job/recruitment/detail/page/RecruitmentDetailPage.jsx
  src/domains/job/search/detail/page/JobSeekDetailPage.jsx
  src/domains/my/detail/MyPost.jsx
  src/domains/my/detail/MyRecentList.jsx
  src/domains/my/detail/components/MyDraftsList.jsx
  src/domains/my/detail/components/PostList.jsx
  src/domains/my/detail/components/RecentList.jsx
  src/domains/my/detail/components/saveToStorage.jsx
  src/domains/my/mypage/components/MyActivity.jsx
  src/routes/RouterPath.js
  src/routes/routes.jsx
  src/services/api/axios.js
  src/store/mypage/useMyBoardStore.js
  src/stories/BoardCategory.stories.jsx
Labels: ✨ Feature

#204 [publishing-23/style] 모달 디자인 수정 & 회원가입 시 폭죽 & 반응형 수정 완료
  package.json
  src/components/app/MobileShare.jsx
  src/components/app/MobileWorkBoard.jsx
  src/components/common/ToastMessage.jsx
  src/components/common/editor/WriteEditor.jsx
  src/components/web/WorkBoard.jsx
  src/constants/animations.js
  src/domains/Find/common/components/OTPInput.jsx
  src/domains/Find/detail/ChangePwPage.jsx
  src/domains/Find/detail/FindPwCheckIDPage.jsx
  src/domains/Find/page/FindIDPage.jsx
  src/domains/community/comment/components/CommentForm.jsx
  src/domains/community/comment/components/CommentList.jsx
  src/domains/community/detail/hook/useEditPost.js
  src/domains/community/detail/page/DetailCommunityPage.jsx
  src/domains/community/write/components/WriteCommunityPostForm.jsx
  src/domains/job/common/components/LastFormLine.jsx
  src/domains/job/common/hook/usePostSubmit.js
  src/domains/job/recruitment/components/form/WriteRecruitmentPostingForm.jsx
  src/domains/job/recruitment/detail/page/RecruitmentDetailPage.jsx
  src/domains/job/recruitment/edit/page/EditRecruitmentPostPage.jsx
  src/domains/job/search/detail/page/JobSeekDetailPage.jsx
  src/domains/job/search/edit/page/EditJobSeekPostPage.jsx
  src/domains/login/common/components/JoinForm.jsx
  src/domains/login/common/components/LoginForm.jsx
  src/domains/login/page/KakaoSuccess.jsx
  src/domains/login/page/NaverSuccess.jsx
  src/domains/my/detail/EditPassword.jsx
  src/domains/my/detail/EditProfile.jsx
  src/domains/my/detail/MyScrap.jsx
  src/domains/my/detail/components/PostList.jsx
  src/hooks/writePost/useSaveDraft.js
  src/services/toast/ToastService.jsx
  src/store/mypage/useFreeDraftStore.js
  src/utils/toastService.js
  yarn.lock
Labels: 🎨 Publishing

#207 [release-v0.25] 25차 버스 출발
  vercel.json
Labels: 🪐 Deploy

#208 [publishing-24/style] 전체 디자인 수정
  src/components/web/PwInputBox.jsx
  src/constants/animations.js
  src/domains/main/common/components/BoardButton.jsx
  src/domains/my/detail/MyPost.jsx
  src/domains/my/detail/components/PostList.jsx
Labels: 🎨 Publishing

#209 [release-v0.26] 26차 버스 출발
  src/components/web/PwInputBox.jsx
  src/constants/animations.js
  src/domains/main/common/components/BoardButton.jsx
  src/domains/my/detail/MyPost.jsx
  src/domains/my/detail/components/PostList.jsx
Labels: 🪐 Deploy

#212 [publishing-25/style] 폭죽 위치 수정 & 구인 마감 inpux 수정 완료
  src/constants/animations.js
  src/domains/job/recruitment/components/form/ClosingDate.jsx
  src/domains/login/common/components/JoinForm.jsx
  src/domains/login/page/KakaoSuccess.jsx
  src/domains/login/page/NaverSuccess.jsx
Labels: 🎨 Publishing

#214 [feature-27/feat] 네이버 서치어드바이저 소유 확인 파일 추가 완료
  public/naverbb7d38c076a4430c36468179380a9db1.html
Labels: ✨ Feature

#220 [release-v0.28] 28차 버스 출발
  src/domains/login/page/KakaoSuccess.jsx
  src/domains/login/page/NaverSuccess.jsx
Labels: 🐞 BugFix
