Repository Book-Job/Frontend, pull requests merged in 2025-04, with the labels that each got.

#10 [feature-01/feat] Vitest & React Testing Library 사용을 위한 세팅 완료
  package.json
  src/setupTests.js
  vite.config.js
  yarn.lock
Labels: 🛠️ Setting

#12 [publishing-02/style] 공통 컴포넌트 퍼블리싱
  package.json
  src/assets/icons/common/common_babyChick.svg
  src/components/web/FreeBoard.jsx
  src/components/web/Header.jsx
  src/components/web/SearchBar.jsx
  src/components/web/ShareViews.jsx
  src/components/web/TagIcon.jsx
  src/components/web/WorkBoard.jsx
  src/stories/FreeBoard.stories.jsx
  src/stories/Header.stories.jsx
  src/stories/SearchBar.stories.jsx
  src/stories/ShareViews.stories.jsx
  src/stories/TagIcon.stories.jsx
  src/stories/WorkBoard.stories.jsx
  tailwind.config.js
  yarn.lock
Labels: 🎨 Publishing

#19 [publishing-06/style] 1차 layout 적용을 위한 pr
  src/App.jsx
  src/components/common/SortDropdown.jsx
  src/components/web/Header.jsx
  src/components/web/JobLabel.jsx
  src/components/web/SearchBar.jsx
  src/domains/.gitkeep
  src/domains/job/common/components/GetEmailAndNickName.jsx
  src/domains/job/common/components/JobFormLine.jsx
  src/domains/job/common/components/WriteFormLine.jsx
  src/domains/job/job-search/WriteJobSearchPosting.jsx
  src/domains/job/job-search/components/WriteJobSearchPostingForm.jsx
  src/domains/job/main/JobMainPage.jsx
  src/domains/job/main/components/CountPost.jsx
  src/domains/job/main/components/JobDropDown.jsx
  src/domains/job/main/components/JobPostSortDropDown.jsx
  src/index.css
  src/main.jsx
  src/stories/FreeBoard.stories.jsx
  src/stories/ShareViews.stories.jsx
  src/stories/WorkBoard.stories.jsx
  src/styles/font.css
  tailwind.config.js
Labels: 🎨 Publishing

#28 [publishing-08/style] 스토리북 오류 해결
  package.json
  src/stories/Footer.stories.jsx
  src/stories/FreeBoard.stories.jsx
  src/stories/Header.stories.jsx
  yarn.lock
Labels: 🐞 BugFix

#26 [publishing-09/style] 메인,회원가입
  src/components/web/InputBox.jsx
  src/components/web/LabelWithInput.jsx
  src/components/web/PwInputBox.jsx
  src/domains/login/common/components/EmailInput.jsx
  src/domains/login/common/components/IDInput.jsx
  src/domains/login/common/components/JoinButton.jsx
  src/domains/login/common/components/JoinForm.jsx
  src/domains/login/common/components/LoginForm.jsx
  src/domains/login/common/components/NicknameInput.jsx
  src/domains/login/common/components/PasswordInput.jsx
  src/domains/login/common/components/SnsLogin.jsx
  src/domains/login/main/LoginMain.jsx
  src/domains/login/main/MemberDataEntry.jsx
  src/domains/main/common/components/BestList.jsx
  src/domains/main/common/components/BoardButton.jsx
  src/domains/main/main/MainPage.jsx
  src/stories/MobileFreeBoard.stories.jsx
  src/stories/MobileMainHeader.stories.jsx
  src/stories/MobileWorkBoard.stories.jsx
Labels: 🎨 Publishing, 🚧 work in process

#36 [publishing-13/style] 특정 유저가 작성한 페이지 & 태그 컴포넌트
  src/assets/icons/common/common_spread_arrow.svg
  src/components/web/BoardCategory.jsx
  src/domains/community/detail/page/UserPosts.jsx
  src/routes/RouterPath.js
  src/routes/routes.jsx
  src/stories/BoardCategory.stories.jsx
Labels: 🎨 Publishing

#39 [publishing-15/style] 비밀번호 수정,일치확인,불일치
  src/domains/my/detail/EditPassword.jsx
  src/domains/my/detail/MyScrap.jsx
  src/domains/my/detail/PasswordMis.jsx
  src/domains/my/mypage/components/MyActivity.jsx
  src/routes/RouterPath.js
  src/routes/routes.jsx
Labels: 🎨 Publishing

#42 [publishing-14/style] 모바일 헤더 완성
  package.json
  src/assets/icons/mobile/mobile_inquiry_gray.svg
  src/assets/icons/mobile/mobile_work_pink.svg
  src/components/app/MobileHeader.jsx
  src/components/app/MobileMainHeader.jsx
  src/components/app/MobileSidebar.jsx
  src/components/web/Footer.jsx
  src/components/web/Header.jsx
  src/domains/main/main/MainPage.jsx
  src/hooks/header/useIsMobile.js
  src/routes/AppRoutes.jsx
  src/routes/Layout.jsx
  src/routes/RouterPath.js
  src/routes/routes.jsx
  src/stories/MobileMainHeader.stories.jsx
  yarn.lock
Labels: 🎨 Publishing

#48 [feature-05/feat] 헤더 고정, 글작성, 맨위로 스크롤 기능 넣기 완성
  src/App.jsx
  src/components/common/ChooseWriteForm.jsx
  src/components/common/PageScrollToTop.jsx
  src/components/common/ScrollAndWriteButton.jsx
  src/components/web/CreatePostButton.jsx
  src/components/web/Header.jsx
  src/components/web/ScrollToTopButton.jsx
  src/routes/AppRoutes.jsx
  src/routes/Layout.jsx
  src/stories/CreatePostButton.stories.jsx
  src/stories/ScrollToTopButton.stories.jsx
Labels: ✨ Feature, 🎨 Publishing

#49 [feature-04/feat] 자유게시판, 구인, 구직 전체 조회 & 자유게시판 검색 기능 작업 완료
  package.json
  src/components/web/Button.jsx
  src/components/web/LabelWithInput.jsx
  src/domains/Find/common/components/PageTitle.jsx
  src/domains/community/main/hook/useCommunityPosts.js
  src/domains/community/main/page/CommunityMainPage.jsx
  src/domains/community/service/postService.js
  src/domains/community/service/useSearchPosts.js
  src/domains/community/write/components/WriteCommunityPostForm.jsx
  src/domains/job/main/components/JobDropDown.jsx
  src/domains/job/main/page/JobMainPage.jsx
  src/domains/job/main/service/jobMainService.js
  src/domains/job/search/service/postService.js
  src/domains/login/common/components/DomainSelector.jsx
  src/domains/login/common/components/EmailInput.jsx
  src/domains/login/common/components/IDInput.jsx
  src/domains/login/common/components/JoinButton.jsx
  src/domains/login/common/components/JoinForm.jsx
  src/domains/login/common/components/LoginForm.jsx
  src/domains/login/common/components/NicknameInput.jsx
  src/domains/login/common/components/PasswordInput.jsx
  src/domains/login/common/components/SnsLogin.jsx
  src/domains/login/page/Join.jsx
  src/domains/login/services/Join.jsx
  src/hooks/search/useDebounce.test.js
  src/services/.gitkeep
  src/services/api/Axios.js
  yarn.lock
Labels: ✨ Feature
