Repository Book-Job/Frontend, pull requests merged in 2025-05, with the labels that each got.

#52 [feature-06/feat] 구인&구직 글 작성 API 연동 완료
  src/domains/job/common/components/LastFormLine.jsx
  src/domains/job/common/components/form/EmploymentType.jsx
  src/domains/job/common/components/form/JobCategory.jsx
  src/domains/job/common/components/form/PersonalInfo.jsx
  src/domains/job/common/components/form/PostContent.jsx
  src/domains/job/common/components/form/PostTitle.jsx
  src/domains/job/common/utils/jobCategories.js
  src/domains/job/recruitment/components/WriteRecruitmentPostingForm.jsx
  src/domains/job/recruitment/components/form/ClosingDate.jsx
  src/domains/job/recruitment/components/form/CompanyWebsite.jsx
  src/domains/job/recruitment/components/form/WorkPlace.jsx
  src/domains/job/recruitment/service/postService.js
  src/domains/job/search/components/WriteJobSearchPostingForm.jsx
  src/domains/job/search/components/form/ContactEmail.jsx
  src/domains/job/search/components/form/WorkExperience.jsx
  src/domains/job/search/service/postService.js
  src/domains/job/service/postService.js
Labels: ✨ Feature

#45 [feature-03/feat] 로그인 / 회원가입 기능 추가
  src/App.jsx
  src/components/app/MobileMainHeader.jsx
  src/components/web/Alert.jsx
  src/components/web/Header.jsx
  src/components/web/Spinner.jsx
  src/domains/Find/common/components/OTPInput.jsx
  src/domains/Find/page/FindIDPage.jsx
  src/domains/login/common/components/EmailInput.jsx
  src/domains/login/common/components/IDInput.jsx
  src/domains/login/common/components/JoinForm.jsx
  src/domains/login/common/components/LoginForm.jsx
  src/domains/login/common/components/NicknameInput.jsx
  src/domains/login/common/components/PasswordInput.jsx
  src/domains/login/services/Join.jsx
  src/domains/login/services/userJoinServices.jsx
  src/domains/login/services/userLoginServices.jsx
  src/routes/RouterPath.js
  src/store/login/useAuthStore.js
  src/stories/Alert.stories.jsx
Labels: ✨ Feature

#54 [feature-08/feat] 마이페이지, 로그인 , 헤더
  package.json
  src/components/web/Header.jsx
  src/domains/login/common/components/EmailInput.jsx
  src/domains/login/common/components/IDInput.jsx
  src/domains/login/common/components/JoinForm.jsx
  src/domains/login/common/components/LoginForm.jsx
  src/domains/login/common/components/NicknameInput.jsx
  src/domains/login/services/userLoginServices.jsx
  src/domains/main/common/components/BestList.jsx
  src/domains/main/common/components/BoardButton.jsx
  src/domains/main/main/MainPage.jsx
  src/domains/my/detail/EditProfile.jsx
  src/domains/my/page/MyPage.jsx
  src/domains/my/services/userMyDataServices.js
  src/routes/Layout.jsx
  src/store/login/useAuthStore.js
  yarn.lock
Labels: ✨ Feature, 🚧 work in process

#61 [feature-09/feat] 아이디 찾기 / 닉네임 변경
  src/components/web/Header.jsx
  src/domains/Find/common/components/InputEmail.jsx
  src/domains/Find/detail/FindIDCompletePage.jsx
  src/domains/Find/page/FindIDPage.jsx
  src/domains/Find/services/useFindIDServices.js
  src/domains/login/common/components/EmailInput.jsx
  src/domains/login/common/components/IDInput.jsx
  src/domains/login/common/components/JoinForm.jsx
  src/domains/login/common/components/NicknameInput.jsx
  src/domains/login/page/MemberDataEntry.jsx
  src/domains/login/services/useJoinServices.js
  src/domains/login/services/useLoginServices.js
  src/domains/my/detail/EditProfile.jsx
  src/domains/my/detail/components/ProfileInfo.jsx
  src/domains/my/mypage/components/MyData.jsx
  src/domains/my/services/userMyDataServices.js
  src/store/find/useFindIDStore.js
  src/store/login/useAuthStore.js
Labels: ✨ Feature

#64 [feature-11/feat] 자유게시판 & 임시 에러 페이지 & 댓글
  eslint.config.js
  index.html
  package.json
  src/components/app/MobileShare.jsx
  src/components/common/TiptapEditor.jsx
  src/components/web/FreeBoard.jsx
  src/components/web/WriteFormLine.jsx
  src/domains/Find/services/useFindIDServices.js
  src/domains/community/comment/components/CommentForm.jsx
  src/domains/community/comment/components/CommentHeader.jsx
  src/domains/community/comment/components/CommentList.jsx
  src/domains/community/detail/hook/useEditPost.js
  src/domains/community/detail/page/DetailCommunityPage.jsx
  src/domains/community/main/page/CommunityMainPage.jsx
  src/domains/community/service/commentService.js
  src/domains/community/service/postService.js
  src/domains/community/service/useSearchPosts.js
  src/domains/community/write/components/WriteCommunityPostForm.jsx
  src/domains/community/write/page/WriteCommunityPostPage.jsx
  src/domains/error/page/ErrorPage.jsx
  src/domains/job/common/components/JobFormLine.jsx
  src/domains/job/common/components/LastFormLine.jsx
  src/domains/job/common/components/form/PersonalInfo.jsx
  src/domains/job/main/components/JobPostSortDropDown.jsx
  src/domains/job/service/postService.js
  src/domains/login/services/useJoinServices.js
  src/domains/login/services/useLoginServices.js
  src/routes/RouterPath.js
  src/routes/routes.jsx
  yarn.lock
Labels: ✨ Feature, 🎨 Publishing

#67 [feature-13/feat] 자유게시판 댓글 완성
  src/components/web/WorkBoard.jsx
  src/domains/community/comment/components/CommentForm.jsx
  src/domains/community/comment/components/CommentHeader.jsx
  src/domains/community/comment/components/CommentList.jsx
  src/domains/community/comment/hooks/useCommentActions.js
  src/domains/community/comment/store/useCommentStore.js
  src/domains/community/detail/page/DetailCommunityPage.jsx
  src/domains/community/main/page/CommunityMainPage.jsx
  src/domains/community/service/commentService.js
  src/domains/community/service/postService.js
  src/domains/community/write/page/WriteCommunityPostPage.jsx
  src/domains/job/common/components/LastFormLine.jsx
Labels: ✨ Feature

#69 [feature-12/feat] 메인페이지 베스트 글 / 헤더 닉네임
  src/components/app/MobileMainHeader.jsx
  src/components/web/Header.jsx
  src/domains/Find/services/useFindPWServices.js
  src/domains/main/common/components/BestList.jsx
  src/domains/main/common/components/BoardButton.jsx
  src/domains/main/main/MainPage.jsx
  src/domains/main/services/useBestServices.js
  src/store/main/useBestStore.js
Labels: ✨ Feature

#72 [feature-14/feat] 구인 페이지 & 자유게시판 상세 조회에서 댓글 수 불러오기 완성
  src/components/app/MobileMainHeader.jsx
  src/components/web/FreeBoard.jsx
  src/components/web/WorkBoard.jsx
  src/domains/community/detail/page/DetailCommunityPage.jsx
  src/domains/community/detail/page/UserPosts.jsx
  src/domains/community/main/page/CommunityMainPage.jsx
  src/domains/community/write/components/WriteCommunityPostForm.jsx
  src/domains/job/common/components/DetailPostLine.jsx
  src/domains/job/common/components/LastFormLine.jsx
  src/domains/job/common/components/form/EmploymentType.jsx
  src/domains/job/common/components/form/PersonalInfo.jsx
  src/domains/job/common/hook/useJobSeekingSearch.js
  src/domains/job/common/hook/useRecruitmentSearch.js
  src/domains/job/common/store/scrap/useScrapStore.js
  src/domains/job/common/utils/employmentTypes.js
  src/domains/job/common/utils/jobCategories.js
  src/domains/job/main/components/CountPost.jsx
  src/domains/job/main/components/JobPostList.jsx
  src/domains/job/main/page/JobMainPage.jsx
  src/domains/job/main/service/jobMainService.js
  src/domains/job/recruitment/components/WriteRecruitmentPostingForm.jsx
  src/domains/job/recruitment/components/form/ClosingDate.jsx
  src/domains/job/recruitment/components/form/CompanyWebsite.jsx
  src/domains/job/recruitment/components/form/Experience.jsx
  src/domains/job/recruitment/detail/hook/useRecruitmentPostDetail.js
  src/domains/job/recruitment/detail/page/RecruitmentDetailPage.jsx
  src/domains/job/recruitment/edit/page/EditRecruitmentPostPage.jsx
  src/domains/job/recruitment/write/page/WriteRecruitmentPostPage.jsx
  src/domains/job/service/postService.js
  src/domains/job/service/scrapJobPost.js
  src/routes/RouterPath.js
  src/routes/routes.jsx
Labels: ✨ Feature

#71 [feature-15/feat] 모바일 헤더 메뉴 / 내가 작성한 글
  src/App.jsx
  src/components/app/MobileMainHeader.jsx
  src/domains/main/common/components/BoardButton.jsx
  src/domains/my/detail/MyPost.jsx
  src/domains/my/detail/components/MyPostHead.jsx
  src/domains/my/detail/components/PostList.jsx
  src/domains/my/services/useMyBoardServices.js
  src/store/mypage/useBoardStore.js
  src/store/mypage/useMyBoardStore.js
Labels: ✨ Feature, 🚧 work in process

#76 [bug-01/fix] 스크랩 오류 수정 완료
  src/components/app/MobileWorkBoard.jsx
  src/components/web/WorkBoard.jsx
  src/domains/job/common/hook/useJobSearch.js
  src/domains/job/common/hook/useJobSeekingSearch.js
  src/domains/job/common/service/postService.js
  src/domains/job/common/utils/getExperienceLabel.js
  src/domains/job/main/components/JobPostList.jsx
  src/domains/job/main/page/JobMainPage.jsx
  src/domains/job/main/service/jobMainService.js
  src/domains/job/recruitment/detail/hook/useRecruitmentPostDetail.js
  src/domains/job/recruitment/detail/page/RecruitmentDetailPage.jsx
  src/domains/job/recruitment/edit/page/EditRecruitmentPostPage.jsx
  src/domains/job/recruitment/write/page/WriteRecruitmentPostPage.jsx
  src/domains/job/scrap/service/scrapService.js
  src/domains/job/scrap/store/useScrapStore.js
  src/domains/job/search/detail/hook/useJobSeekPostDetail.js
  src/domains/job/search/detail/page/JobSeekDetailPage.jsx
  src/domains/job/search/edit/page/EditJobSeekPostPage.jsx
  src/domains/job/search/write/page/WriteJobSearchPostPage.jsx
  src/domains/my/detail/MyScrap.jsx
  src/store/main/useBestStore.js
Labels: 🐞 BugFix

#78 [feature-18/feat] 관련 글 불러오기 & 구인, 구직 상세 페이지에서 스크랩
  src/domains/community/detail/components/RelatedPosts.jsx
  src/domains/community/detail/page/DetailCommunityPage.jsx
  src/domains/job/main/page/JobMainPage.jsx
  src/domains/job/main/service/jobMainService.js
  src/domains/job/recruitment/detail/components/RelatedRecruitmentPosts.jsx
  src/domains/job/recruitment/detail/page/RecruitmentDetailPage.jsx
  src/domains/job/search/detail/components/RelatedJobSearchPosts.jsx
  src/domains/job/search/detail/page/JobSeekDetailPage.jsx
Labels: ✨ Feature

#79 [feature-17/feat] 회원탈퇴, 비밀번호 변경 페이지 접근 권한 설정
  src/domains/Find/detail/ChangePwPage.jsx
  src/domains/Find/detail/FindPwCheckIDPage.jsx
  src/domains/Find/services/useFindPWServices.js
  src/domains/main/services/useBestServices.js
  src/domains/my/detail/EditPassword.jsx
  src/domains/my/detail/EditProfile.jsx
  src/domains/my/detail/components/MembershipPwCheck.jsx
  src/domains/my/detail/components/ProfileInfo.jsx
  src/domains/my/services/userMyDataServices.js
  src/store/login/useAuthStore.js
Labels: ✨ Feature, 🎨 Publishing

#81 [publishing-17/style] 모든 로딩 spinner 수정 & 모든 alert Toastify 수정 & 작업한 페이지 반응형 확인
  src/App.jsx
  src/components/app/MobileFreeBoard.jsx
  src/components/app/MobileWorkBoard.jsx
  src/components/web/FreeBoard.jsx
  src/components/web/WorkBoard.jsx
  src/domains/Find/common/components/InputEmail.jsx
  src/domains/Find/detail/FindPwCheckIDPage.jsx
  src/domains/community/comment/components/CommentForm.jsx
  src/domains/community/comment/components/CommentHeader.jsx
  src/domains/community/comment/components/CommentList.jsx
  src/domains/community/comment/store/useCommentStore.js
  src/domains/community/detail/components/RelatedPosts.jsx
  src/domains/community/detail/hook/useEditPost.js
  src/domains/community/detail/page/DetailCommunityPage.jsx
  src/domains/community/main/page/CommunityMainPage.jsx
  src/domains/community/write/components/WriteCommunityPostForm.jsx
  src/domains/community/write/page/WriteCommunityPostPage.jsx
  src/domains/job/common/components/DetailPostLine.jsx
  src/domains/job/common/components/LastFormLine.jsx
  src/domains/job/common/hook/usePostSubmit.js
  src/domains/job/main/components/JobDropDown.jsx
  src/domains/job/main/components/JobPostList.jsx
  src/domains/job/main/page/JobMainPage.jsx
  src/domains/job/main/service/jobMainService.js
  src/domains/job/recruitment/components/form/ClosingDate.jsx
  src/domains/job/recruitment/detail/components/RelatedRecruitmentPosts.jsx
  src/domains/job/recruitment/detail/page/RecruitmentDetailPage.jsx
  src/domains/job/recruitment/edit/page/EditRecruitmentPostPage.jsx
  src/domains/job/search/detail/components/RelatedJobSearchPosts.jsx
  src/domains/job/search/detail/hook/useJobSeekPostDetail.js
  src/domains/job/search/detail/page/JobSeekDetailPage.jsx
  src/domains/job/search/edit/page/EditJobSeekPostPage.jsx
  src/domains/my/detail/components/PostList.jsx
  src/utils/.gitkeep
  src/utils/toastService.js
Labels: 🎨 Publishing

#83 [feature-19/feat] 로그아웃, 헤더 수정
  src/components/app/MobileHeader.jsx
  src/components/app/MobileMainHeader.jsx
  src/components/web/Header.jsx
  src/domains/login/common/components/LoginForm.jsx
  src/domains/login/services/useLoginServices.js
  src/domains/my/detail/EditProfile.jsx
  src/domains/my/detail/components/ProfileInfo.jsx
  src/domains/my/page/MyPage.jsx
  src/domains/my/services/userMyDataServices.js
  src/store/login/useAuthStore.js
Labels: ✨ Feature, 🎨 Publishing

#86 [bug-03/fix] 메인페이지 글 최신화/마이페이지 접근 권한
  src/components/app/MobileMainHeader.jsx
  src/domains/community/comment/components/CommentForm.jsx
  src/domains/community/comment/components/CommentList.jsx
  src/domains/job/common/hook/usePostSubmit.js
  src/domains/main/common/components/BestList.jsx
  src/domains/main/common/components/BoardButton.jsx
  src/domains/main/main/MainPage.jsx
  src/domains/my/page/MyPage.jsx
  src/routes/RouterPath.js
  src/store/main/useBestStore.js
Labels: 🐞 BugFix

#92 [feature-21/feat] 카카오 로그인 기능
  .gitignore
  src/components/web/FreeBoard.jsx
  src/domains/community/main/page/CommunityMainPage.jsx
  src/domains/job/main/components/JobPostSortDropDown.jsx
  src/domains/job/main/page/JobMainPage.jsx
  src/domains/job/recruitment/detail/components/RelatedRecruitmentPosts.jsx
  src/domains/job/search/detail/components/RelatedJobSearchPosts.jsx
  src/domains/login/common/components/KakaoLogin.jsx
  src/domains/login/common/components/NaverLogin.jsx
  src/domains/login/common/components/SnsLogin.jsx
  src/domains/login/page/LoginMain.jsx
  src/domains/login/services/useLoginServices.js
  src/domains/my/detail/MyScrap.jsx
  src/index.css
  src/routes/RouterPath.js
  src/store/login/useAuthStore.js
Labels: ✨ Feature

#98 [bug-06/fix] 글 작성시에 라이브러리 정상적으로 작동 안하는 버그 해결 완료
  src/App.jsx
  src/components/common/TiptapEditor.jsx
  src/components/common/WriteEditor.jsx
Labels: 🐞 BugFix
