Repository Book-Job/Frontend, pull requests merged in 2025-09, with the labels that each got.

#306 [feature-41/feat] 배너 추가 / 채용 글 등록 버튼 추가 / 바로가기 링크 색상 변경
  package.json
  src/assets/banner/coffee_event_app_banner.gif
  src/assets/banner/coffee_event_banner.gif
  src/assets/banner/pwa_app_banner.jpg
  src/assets/banner/pwa_banner.jpg
  src/assets/icons/common/main_logo.gif
  src/components/app/MobileMainHeader.jsx
  src/components/common/Banner.jsx
  src/components/web/Header.jsx
  src/domains/job/recruitment/detail/page/RecruitmentDetailPage.jsx
  src/domains/main/main/MainPage.jsx
  tailwind.config.js
  yarn.lock
Labels: ✨ Feature

#307 [release-v1.0] 1.1차 버스 출발
  package.json
  src/assets/banner/coffee_event_app_banner.gif
  src/assets/banner/coffee_event_banner.gif
  src/assets/banner/pwa_app_banner.jpg
  src/assets/banner/pwa_banner.jpg
  src/assets/icons/common/main_logo.gif
  src/components/app/MobileMainHeader.jsx
  src/components/common/Banner.jsx
  src/components/web/Header.jsx
  src/domains/job/recruitment/detail/page/RecruitmentDetailPage.jsx
  src/domains/main/main/MainPage.jsx
  tailwind.config.js
  yarn.lock
Labels: 🪐 Deploy

#308 [Feature 41/feat] 배너 수정
  src/assets/banner/coffee_event_app_banner.gif
  src/assets/banner/coffee_event_banner.gif
Labels: 📂 Docs, ✨ Feature

#316 [bug-34/fix] 설문 모달, 커피이벤트 모달 동시 열림 오류/ 이메일 인증 스타일 오류
  src/App.jsx
  src/components/web/FreeBoard.jsx
  src/domains/login/common/components/EmailInput.jsx
  src/domains/main/common/components/Modals/CoffeeEvent.jsx
  src/domains/main/common/components/Modals/EventModal.jsx
  src/domains/main/common/components/Modals/ModalManager.jsx
  src/domains/main/common/components/Modals/SurveyModal.jsx
  src/domains/main/common/components/Modals/modalConfigs.js
  src/domains/main/main/MainPage.jsx
Labels: 🐞 BugFix

#329 [publishing-31/style] 구인구직 최신글 (오늘의 구인구직)
  src/domains/main/common/components/BestList.jsx
  src/domains/main/common/components/BoardButton.jsx
  src/domains/main/main/MainPage.jsx
Labels: 🎨 Publishing

#341 [bug-37/fix] 구글 검색 시 버셀 주소 나오는 부분 수정/네이버 깃허브 수정
  index.html
  vercel.json
Labels: 🐞 BugFix

#349 [feature-47/feat] 자유게시판 대댓글 기능 완성
  src/domains/community/comment/components/CommentList.jsx
  src/domains/community/service/commentService.js
Labels: ✨ Feature

#357 [bug-30/fix] 좋아요 수정 & 리액트 캐러셀 삽입 완료
  src/components/common/Banner.jsx
  src/components/common/LikeCountReadOnly.jsx
Labels: 🐞 BugFix

#362 [bug-39/fix] 자유게시판 좋아요 내가 눌렀는지 여부 수정 완료
  src/components/common/LikeCount.jsx
  src/domains/community/detail/page/DetailCommunityPage.jsx
Labels: 🐞 BugFix

#363 [release-v2.0] 2.0차 버스 출발
  src/components/common/LikeCount.jsx
  src/domains/community/detail/page/DetailCommunityPage.jsx
Labels: 🪐 Deploy

#361 [bug-38/fix] 이메일 인증 재전송/ 팝업 수정/ 메인 베스트 아이콘 위치 수정
  src/App.jsx
  src/domains/Find/common/components/OTPInput.jsx
  src/domains/login/common/components/EmailInput.jsx
  src/domains/main/common/components/BestList.jsx
  src/domains/main/common/components/Modals/EventModal.jsx
  src/domains/main/common/components/Modals/ModalManager.jsx
Labels: 🐞 BugFix

#364 [release-v1.20] 1.20차 버스 출발
  src/App.jsx
  src/domains/Find/common/components/OTPInput.jsx
  src/domains/login/common/components/EmailInput.jsx
  src/domains/main/common/components/BestList.jsx
  src/domains/main/common/components/Modals/EventModal.jsx
  src/domains/main/common/components/Modals/ModalManager.jsx
Labels: 🪐 Deploy
