Repository Book-Job/Frontend, pull requests merged in 2025-10, with the labels that each got.

#369 [bug-41/fix] 최신글 바로가기 경로 수정 /MainPage 뒤로가기 복귀 기능 보강
  src/domains/main/common/components/BestList.jsx
  src/domains/main/main/MainPage.jsx
Labels: 🐞 BugFix

#370 [release-v1.22] 1.22차 버스 출발
  src/domains/main/common/components/BestList.jsx
  src/domains/main/main/MainPage.jsx
Labels: 🪐 Deploy

#371 [bug-41/fix] 최신글 바로가기 경로 수정 /MainPage 뒤로가기 복귀 기능 보강
  src/domains/main/common/components/BestList.jsx
  src/domains/main/services/useBestServices.js
Labels: 🐞 BugFix

#378 [refactor/vercel-settings] 버셀 performance 수정 완료
  package.json
  src/App.jsx
  yarn.lock
Labels: 🔥 perf-improvement

#380 [publishing-34/style] 구인 & 구직 탭 디자인 수정 완료
  src/domains/job/main/components/JobDropDown.jsx
  src/domains/main/common/components/BestList.jsx
Labels: 🎨 Publishing
