Repository Book-Job/Frontend, pull requests merged in 2025-07, with the labels that each got.

#225 [bug-15/fix] 회원가입 & 로그인 구분해서 폭죽 적용하기 완료
  src/domains/login/page/KakaoSuccess.jsx
  src/domains/login/page/NaverSuccess.jsx
  src/store/login/useAuthStore.js
Labels: ✨ Feature

#229 [feature-36/feat] 이용약관 & 개인정보 연결하기 | 구인 마감 인풋박스 가운데 | 구글 검색 했을 때 아이콘 수정하기 | meta-tag 수정 완료
  index.html
  src/components/web/Footer.jsx
  src/domains/job/recruitment/components/form/ClosingDate.jsx
  src/domains/main/main/MainPage.jsx
  src/domains/policy/page/PrivacyPolicy.jsx
  src/domains/policy/page/TermsOfService.jsx
  src/routes/RouterPath.js
  src/routes/routes.jsx
Labels: ✨ Feature, 🎨 Publishing

#232 [publishing-25/style] 설문조사 배너에서 팝업으로 띄우기 완료
  src/assets/banner/app_banner.png
  src/assets/banner/web_banner.png
  src/domains/community/main/page/CommunityMainPage.jsx
  src/domains/job/main/page/JobMainPage.jsx
  src/domains/main/common/components/SurveyModal.jsx
  src/domains/main/main/MainPage.jsx
Labels: ✨ Feature

#231 [bug-16/fix] 닉네임 변경시 수정 알림/PWA 웹 url 창 없이 띄우기/PWA자동 설치 기능 추가
  index.html
  public/favicon-144x144.png
  public/favicon-16x16.png
  public/favicon-192x192.png
  public/favicon-36x36.png
  public/favicon-512x512.png
  public/favicon1-16x16.png
  public/icon-1280x720.png
  public/icon-360x640.png
  public/icon-540x720.png
  public/manifest.json
  src/App.jsx
  src/components/common/PwaPopUp.jsx
  src/domains/login/common/components/JoinButton.jsx
  src/domains/login/common/components/KakaoLogin.jsx
  src/domains/login/common/components/LoginForm.jsx
  src/domains/login/common/components/NaverLogin.jsx
  src/domains/login/common/components/SnsLogin.jsx
  src/domains/login/services/useLoginServices.js
  src/domains/main/common/components/BestList.jsx
  src/domains/main/services/useBestServices.js
  src/domains/my/detail/components/ProfileInfo.jsx
  src/services/api/axios.js
  tailwind.config.js
  vite.config.js
Labels: 🐞 BugFix, ✨ Feature

#236 [release-v0.31] 31차 버스 출발
  index.html
  public/favicon-144x144.png
  public/favicon-16x16.png
  public/favicon-192x192.png
  public/favicon-36x36.png
  public/favicon-512x512.png
  public/favicon1-16x16.png
  public/icon-1280x720.png
  public/icon-360x640.png
  public/icon-540x720.png
  public/manifest.json
  src/App.jsx
  src/assets/banner/app_banner.png
  src/assets/banner/web_banner.png
  src/components/common/PwaPopUp.jsx
  src/domains/community/main/page/CommunityMainPage.jsx
  src/domains/job/main/page/JobMainPage.jsx
  src/domains/login/common/components/JoinButton.jsx
  src/domains/login/common/components/KakaoLogin.jsx
  src/domains/login/common/components/LoginForm.jsx
  src/domains/login/common/components/NaverLogin.jsx
  src/domains/login/common/components/SnsLogin.jsx
  src/domains/login/services/useLoginServices.js
  src/domains/main/common/components/BestList.jsx
  src/domains/main/common/components/SurveyModal.jsx
  src/domains/main/main/MainPage.jsx
  src/domains/main/services/useBestServices.js
  src/domains/my/detail/components/ProfileInfo.jsx
  src/services/api/axios.js
  tailwind.config.js
  vite.config.js
Labels: 🪐 Deploy

#235 [bug-18/fix] 임시비밀번호 발급 입력창 수정/PWA자동 설치 기능 수정
  index.html
  src/components/common/PwaPopUp.jsx
  src/domains/Find/detail/FindPwCheckIDPage.jsx
  src/domains/Find/detail/FindPwEnterID.jsx
  vite.config.js
  yarn.lock
Labels: 🐞 BugFix, 🚧 work in process

#237 [release-v0.32] 32차 버스 출발
  index.html
  src/components/common/PwaPopUp.jsx
  src/domains/Find/detail/FindPwCheckIDPage.jsx
  src/domains/Find/detail/FindPwEnterID.jsx
  vite.config.js
  yarn.lock
Labels: 🪐 Deploy

#239 [bug-19/fix] 최근본 페이지 이미지만 있는거 아무표시 없음/PWA자동 설치 수정 완료
  src/components/app/MobileHeader.jsx
  src/components/app/MobileMainHeader.jsx
  src/components/app/MobileWorkBoard.jsx
  src/components/common/PwaPopUp.jsx
  src/components/web/FreeBoard.jsx
  src/components/web/Header.jsx
  src/components/web/WorkBoard.jsx
  src/domains/Find/detail/ChangePwPage.jsx
  src/domains/community/detail/page/UserPosts.jsx
  src/domains/community/write/components/WriteCommunityPostForm.jsx
  src/domains/job/main/page/JobMainPage.jsx
  src/domains/job/recruitment/write/page/WriteRecruitmentPostPage.jsx
  src/domains/job/search/write/page/WriteJobSearchPostPage.jsx
  src/domains/login/common/components/LoginForm.jsx
  src/domains/main/common/components/BestList.jsx
  src/domains/my/detail/EditPassword.jsx
  src/domains/my/detail/MyPost.jsx
  src/domains/my/detail/MyRecentList.jsx
  src/domains/my/detail/MyScrap.jsx
  src/domains/my/detail/components/PostList.jsx
  src/domains/my/detail/components/RecentList.jsx
  src/domains/my/detail/components/saveToStorage.jsx
  src/main.jsx
  src/routes/AppRoutes.jsx
  src/routes/Layout.jsx
  src/routes/routes.jsx
  src/store/mypage/useFreeDraftStore.js
Labels: 🐞 BugFix

#240 [bug-17/fix] 구인 마감 인풋 박스에(IOS)에서 날짜 가운데로 오는 오류 & 댓글(오른쪽 정렬) 수정 완료
  src/assets/banner/app_banner.jpg
  src/assets/banner/app_banner.png
  src/assets/banner/pwa_banner.jpg
  src/assets/banner/web/web_Banner.png
  src/assets/banner/web_banner.jpg
  src/assets/banner/web_banner.png
  src/components/app/MobileWorkBoard.jsx
  src/components/common/Banner.jsx
  src/components/common/BannerExample.jsx
  src/components/common/editor/ImageBubbleMenu.jsx
  src/components/web/Header.jsx
  src/components/web/JobLabel.jsx
  src/components/web/WorkBoard.jsx
  src/constants/animations.js
  src/domains/Find/common/components/NewPasswordInput.jsx
  src/domains/Find/common/components/OTPInput.jsx
  src/domains/Find/detail/FindPwCheckIDPage.jsx
  src/domains/Find/detail/FindPwEnterID.jsx
  src/domains/Find/page/FindIDPage.jsx
  src/domains/community/comment/components/CommentForm.jsx
  src/domains/community/comment/components/CommentList.jsx
  src/domains/community/detail/page/DetailCommunityPage.jsx
  src/domains/community/main/page/CommunityMainPage.jsx
  src/domains/community/write/components/WriteCommunityPostForm.jsx
  src/domains/community/write/page/WriteCommunityPostPage.jsx
  src/domains/job/common/components/form/EmploymentType.jsx
  src/domains/job/common/components/form/JobCategory.jsx
  src/domains/job/common/components/form/PostContent.jsx
  src/domains/job/common/components/form/PostTitle.jsx
  src/domains/job/recruitment/components/form/ClosingDate.jsx
  src/domains/job/recruitment/components/form/Experience.jsx
  src/domains/job/recruitment/components/form/WorkPlace.jsx
  src/domains/job/recruitment/detail/page/RecruitmentDetailPage.jsx
  src/domains/job/recruitment/write/page/WriteRecruitmentPostPage.jsx
  src/domains/job/search/components/form/ContactEmail.jsx
  src/domains/job/search/components/form/WorkExperience.jsx
  src/domains/job/search/detail/page/JobSeekDetailPage.jsx
  src/domains/job/search/edit/page/EditJobSeekPostPage.jsx
  src/domains/job/search/write/page/WriteJobSearchPostPage.jsx
  src/domains/login/common/components/EmailInput.jsx
  src/domains/login/common/components/IDInput.jsx
  src/domains/login/common/components/LoginForm.jsx
  src/domains/login/common/components/NicknameInput.jsx
  src/domains/login/common/components/PasswordInput.jsx
  src/domains/main/common/components/SurveyModal.jsx
  src/domains/main/main/MainPage.jsx
  src/domains/my/detail/EditPassword.jsx
  src/domains/my/detail/MyPost.jsx
  src/domains/my/detail/components/MembershipPwCheck.jsx
  src/domains/my/detail/components/ProfileInfo.jsx
  src/domains/my/page/MyPage.jsx
  src/hooks/writePost/useTitleValidation.js
  src/index.css
  tailwind.config.js
Labels: 🐞 BugFix

#251 [bug-22/fix] 구인 구직 글 수정시 내용 없는 오류 수정
  src/domains/job/recruitment/components/form/WriteRecruitmentPostingForm.jsx
  src/domains/job/recruitment/detail/page/RecruitmentDetailPage.jsx
  src/domains/job/recruitment/edit/page/EditRecruitmentPostPage.jsx
  src/domains/job/recruitment/write/page/WriteRecruitmentPostPage.jsx
  src/domains/job/search/components/WriteJobSearchPostingForm.jsx
  src/domains/job/search/detail/page/JobSeekDetailPage.jsx
  src/domains/job/search/write/page/WriteJobSearchPostPage.jsx
  src/domains/my/detail/components/MyDraftsList.jsx
  src/store/mypage/useFreeDraftStore.js
Labels: 🐞 BugFix

#254 [bug-23/fix] 1차 release 전 버그 수정 완료
  package.json
  src/assets/icons/common/common_tag_othersite.svg
  src/assets/styles/datepicker.css
  src/components/app/MobileWorkBoard.jsx
  src/components/web/Skeleton.jsx
  src/components/web/WorkBoard.jsx
  src/domains/job/common/utils/getExperienceLabelFromExperience.js
  src/domains/job/main/components/JobPostList.jsx
  src/domains/job/recruitment/components/form/ClosingDate.jsx
  src/domains/job/recruitment/detail/page/RecruitmentDetailPage.jsx
  src/domains/job/search/detail/page/JobSeekDetailPage.jsx
  src/hooks/writePost/useEditorInstance.js
  vite.config.js
  yarn.lock
Labels: 🐞 BugFix

#258 [bug-24/fix]외부아이콘 tag 스토리북에서 삭제
  src/stories/TagIcon.stories.jsx
Labels: 🐞 BugFix

#259 [bug-24/fix] 사용하지 않는 스토리북 othersite 삭제
  src/stories/MobileWorkBoard.stories.jsx
  src/stories/WorkBoard.stories.jsx
Labels: 🐞 BugFix

#252 [bug-21/fix] 자유게시판 닉네임 길이 제한 / 다른사람 작성글 보기, 내가 작성한 글, 바로가기 기능 추가
  src/components/app/MobileMainHeader.jsx
  src/components/web/FreeBoard.jsx
  src/components/web/Header.jsx
  src/domains/community/detail/page/UserPosts.jsx
  src/domains/community/write/components/WriteCommunityPostForm.jsx
  src/domains/main/main/MainPage.jsx
  src/domains/my/detail/components/PostList.jsx
  src/domains/my/detail/components/ProfileInfo.jsx
Labels: 🐞 BugFix

#272 [release-v0.34] 34차 버스 출발
  src/stories/BgNoneButton.stories.jsx
Labels: 🪐 Deploy

#273 [bug-27/fix] style 다크모드 백그라운드 변경
  index.html
Labels: 🎨 Publishing

#274 [release-v0.35] 35차 버스 출발
  index.html
Labels: 🪐 Deploy

#276 [bug-28/fix] skeleton ui 추가 & 자유게시판 글 없는 경우 수정
  index.html
  package.json
  src/components/common/Banner.jsx
  src/components/common/ContentRenderer.jsx
  src/components/common/ImageWithSkeleton.jsx
  src/components/common/editor/EditorToolbar.jsx
  src/domains/community/comment/store/useCommentStore.js
  src/domains/community/detail/hook/useDetailPost.js
  src/domains/community/detail/hook/useEditPost.js
  src/domains/community/detail/page/DetailCommunityPage.jsx
  src/domains/community/main/page/CommunityMainPage.jsx
  src/domains/job/common/components/JobInfiniteScroll.jsx
  src/domains/job/recruitment/detail/page/RecruitmentDetailPage.jsx
  src/domains/job/search/detail/page/JobSeekDetailPage.jsx
  src/domains/main/common/components/SurveyModal.jsx
  src/domains/my/detail/EditProfile.jsx
  src/domains/my/detail/MyScrap.jsx
  src/hooks/writePost/useEditorInstance.js
  yarn.lock
Labels: 🐞 BugFix

#277 [release-v0.36] 36차 버스 출발
  index.html
  package.json
  src/components/common/Banner.jsx
  src/components/common/ContentRenderer.jsx
  src/components/common/ImageWithSkeleton.jsx
  src/components/common/editor/EditorToolbar.jsx
  src/domains/community/comment/store/useCommentStore.js
  src/domains/community/detail/hook/useDetailPost.js
  src/domains/community/detail/hook/useEditPost.js
  src/domains/community/detail/page/DetailCommunityPage.jsx
  src/domains/community/main/page/CommunityMainPage.jsx
  src/domains/job/common/components/JobInfiniteScroll.jsx
  src/domains/job/recruitment/detail/page/RecruitmentDetailPage.jsx
  src/domains/job/search/detail/page/JobSeekDetailPage.jsx
  src/domains/main/common/components/SurveyModal.jsx
  src/domains/my/detail/EditProfile.jsx
  src/domains/my/detail/MyScrap.jsx
  src/hooks/writePost/useEditorInstance.js
  yarn.lock
Labels: 🪐 Deploy

#279 [release-v0.37] 37차 버스 출발
  src/hooks/writePost/useEditorInstance.js
Labels: 🪐 Deploy
